global using Moq;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using MSC.DemoLogic.CalculationStrategy;
global using MSC.DemoLogic.Interfaces;
global using MSC.DemoLogic.Implementations;
global using MSC.DemoLogic.Types;
global using MSC.DemoLogic.Enums;
global using MSC.DemoLogic.Exceptions;
global using MSC.DemoLogic.Services;